/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      screens: {
        'grid-fit': '1305px',
      },
      colors: {
        primary: '#020F5B',
        accent: '#062EFE',
        'text-muted': '#46508A',
        divider: '#B8C6E5',
        'card-bg': '#F5F7FA',
        bg: '#FFFFFF',
        'neutral-100': '#F0F1FA',
        'partner-border': '#D8D9E7',
      },
      fontFamily: {
        sans: ['Poppins', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'section-label': '0.75rem',
        'stat-number': '60px',
        'stat-number-sm': '34px',
        'stat-plus': '36px',
        'stat-plus-sm': '20px',
        'stat-title': '28px',
        'stat-title-sm': '28px',
        'stat-desc': '14px',
        'stat-desc-sm': '20px',
        'proven-title': '52px',
        'proven-title-sm': '34px',
        'proven-subtitle': '20px',
        'proven-subtitle-sm': '16px',
        'proven-body': '18px',
        'proven-body-sm': '14px',
      },
      fontWeight: {
        'section-label': '500',
      },
      lineHeight: {
        'stat-number': '72px',
        'stat-number-sm': '40px',
        'stat-plus': '48px',
        'stat-plus-sm': '28px',
        'stat-title': '36px',
        'stat-title-sm': '34px',
        'stat-desc': '20px',
        'stat-desc-sm': '28px',
        'proven-title': '68px',
        'proven-title-sm': '42px',
        'proven-subtitle': '28px',
        'proven-subtitle-sm': '24px',
        'proven-body': '28px',
        'proven-body-sm': '22px',
      },
      borderRadius: {
        card: '10px',
      },
      boxShadow: {
        card: '0 1px 3px rgba(0, 0, 0, 0.06)',
      },
      width: {
        'section-underline': '72px',
        'our-impact': '408px',
        'impact-stats': '184px',
        'proven': '744px',
        'partner-card': '92px',
      },
      height: {
        'section-underline': '4px',
        'partner-card': '68px',
      },
      maxWidth: {
        'page': '1305px',
        'proven': '744px',
      },
      spacing: {
        'section-label-gap': '52px',
        'section-label-gap-mobile': '24px',
        'two-col-gap': '40px',
        'headline-to-stats': '50px',
        'headline-to-stats-mobile': '40px',
        'stat-block-gap': '32px',
        'stat-inner-gap': '8px',
        'proven-gap': '24px',
        'block-gap': '2rem',
        'column-gap': '3rem',
        'page-x': '1.5rem',
        'page-x-mobile': '1rem',
        'grid-gap': '1rem',
        'card-padding': '1.25rem',
        'partner-gap-x': '18.5px',
        'partner-gap-y': '16px',
        'partner-section': '80px',
        'partner-section-mobile': '48px',
      },
    },
  },
  plugins: [],
}
